implemented Single Activity
maxx1997/AlinkaHomyak pull request #2
Opened 2021-03-05 23:16 UTC by maxx1997

![Screenshot_1](https://user-images.githubusercontent.com/79761591/110184858-4e297c80-7e2a-11eb-8be5-6a45a9835ab0.png)
![Screenshot_2](https://user-images.githubusercontent.com/79761591/110184859-4f5aa980-7e2a-11eb-88c4-d7059261b704.png)

Добавленные цвета:
colorPrimary #fb8c00
colorAccent "#ffbd45

2021-03-09 08:26 UTC, elestatte87 commented on app/src/main/res/layout/activity_main.xml
> +
Тебе самому удобно когда куча мусора в коде ? Сделай нормальное форматирование, убери весь мусор, наведи порядок.

2021-03-09 08:26 UTC, elestatte87 commented on app/src/main/res/layout/activity_main.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
Гениально - constraint layout в constraint layout. Нет таких мощных решений у нас не будет.

2021-03-09 08:26 UTC, elestatte87 commented on app/src/main/java/com/gmail/alinkahomyak/ContactDetailFragment.kt
> +
грязь...

2021-03-09 08:26 UTC, elestatte87 commented on app/src/main/java/com/gmail/alinkahomyak/ContactDetailFragment.kt
> +        (activity as AppCompatActivity).supportActionBar?.title = ("Детали контакта")
("Детали контакта") ? зачем скобки. почему не в ресурсах ?

2021-03-09 08:26 UTC, elestatte87 commented on app/src/main/java/com/gmail/alinkahomyak/ContactDetailFragment.kt
> +        (activity as AppCompatActivity).supportActionBar?.title = ("Детали контакта")
Почему в onCreateView это делаешь а не в onViewCreated ?

2021-03-09 08:26 UTC, elestatte87 commented on app/src/main/res/values/strings.xml
> +    <string name="description">Description</string>
Мощно

2021-03-09 08:26 UTC, elestatte87 commented on app/src/main/res/layout/contact_list_fragment.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
Нет давай-ка сразу отдельно верстку сделай ячейки и тут пока сделай инклуд этой верстки

2021-03-09 08:26 UTC, elestatte87 commented on app/src/main/res/layout/contact_list_fragment.xml
> +        android:layout_marginStart="14dp"
можно заменить одним horizontal...

2021-03-09 08:31 UTC, elestatte87 commented on app/src/main/java/com/gmail/alinkahomyak/MainActivity.kt
> +         val toolbar = findViewById<View>(R.id.activityToolbar) as Toolbar
findViewById<View> -> findViewById<Toolbar>

2021-03-09 08:33 UTC, elestatte87 commented on app/src/main/java/com/gmail/alinkahomyak/MainActivity.kt
> +            val fragmentTransaction: FragmentTransaction = supportFragmentManager.beginTransaction()
upportFragmentManager
    .beginTransaction()
    ..add(R.id.dataContainer, ContactListFragment())

2021-03-09 08:35 UTC, elestatte87 commented on app/src/main/java/com/gmail/alinkahomyak/MainActivity.kt
> +            val fragmentTransaction: FragmentTransaction = supportFragmentManager.beginTransaction()
переписать

2021-03-09 08:39 UTC, elestatte87 commented on app/src/main/res/layout/contact_detail_fragment.xml
> +        android:textSize="18sp"
Очень много дубляжа вынеси в стили повторяющиеся вещи:
android:textSize="18sp"
android:textColor="@color/white"
android:fontFamily="sans-serif-medium"

2021-03-09 08:47 UTC, elestatte87 commented on app/src/main/res/layout/contact_detail_fragment.xml
> +    android:background="@color/grey">
Цвет бэкграунда разве из темы не берется ?

2021-03-09 08:58 UTC, elestatte87 commented on app/src/main/res/values/themes.xml
> +        <item name="colorPrimary">@color/colorPrimary</item>
Прочитай задание

2021-03-09 08:59 UTC, elestatte87 commented on app/src/main/res/values-night/themes.xml
> +        <item name="colorPrimary">@color/colorAccent</item>
Прочитай задание

2021-03-09 08:59 UTC, elestatte87 commented on app/src/main/java/com/gmail/alinkahomyak/ContactDetailFragment.kt
> +class ContactDetailFragment: Fragment() {
Прочитай задание - нет передачи аргумента

2021-03-09 09:16 UTC, elestatte87 commented on app/src/main/res/layout/contact_list_fragment.xml
> +    android:onClick="onclickListFragment"
"то неприменимо будет дальнейшем. Тем более в задании четко указано - передача в качестве аргумента id контакта

2021-03-14 18:28 UTC, maxx1997 reviewed
Исправил все 16 недоработок

2021-03-15 04:56 UTC, elestatte87 commented on app/src/main/java/com/gmail/alinkahomyak/ContactDetailFragment.kt
> +        fun getFragID(args:Bundle?):ContactDetailFragment{
1) Есть псевдо соглашение называть newInstance. getFragID в любом случае неудачный нейминг
2) Изучите apply в kotlin примените тут

2021-03-15 04:58 UTC, elestatte87 commented on app/src/main/java/com/gmail/alinkahomyak/ContactDetailFragment.kt
> +
Максим разберитесь пожалуйста с форматированием. Поставьте везде правильные отступы уберите лишние пустые строки. Это не сложно сделать (выделите весь текст нажмите alt+ctrl+l)

2021-03-15 05:05 UTC, elestatte87 commented on app/src/main/java/com/gmail/alinkahomyak/ContactListFragment.kt
> +        view.setOnClickListener {
Очень странный кусок кода. Что-то конструируется и никуда не передается. Ни bundle ни фрагмент
Конструирование бандла логичней перенести в статик метод получения фрагмента
Если совсем придираться то смысл получать инстанс фрагмента есть только если доходим до replace(R.id.fragmentContainer, ContactDetailFragment()). У вас тут ?.replace - что подразумевает то что фрамент может быть создан но не использован

2021-03-15 05:07 UTC, elestatte87 commented on app/src/main/java/com/gmail/alinkahomyak/MainActivity.kt
> +        val contactListFragment = ContactListFragment()
Для единообразия создайте статик метод как в другом фрагменте

2021-03-15 05:09 UTC, elestatte87 commented on app/src/main/res/layout/activity_main.xml
>  <androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
ConstraintLayout замените на framelayout - он тут не нужен

2021-03-15 05:13 UTC, elestatte87 commented on app/src/main/res/layout/contact_detail_fragment.xml
> +    android:weightSum="8">
Не очень понятно зачем вам тут веса. Они вам действительно нужны ?

2021-03-15 05:14 UTC, elestatte87 commented on app/src/main/res/layout/contact_detail_fragment.xml
> +            android:layout_width="0dp"
сделайте лучше проще - 120 на 120

2021-03-15 05:16 UTC, elestatte87 commented on app/src/main/res/layout/contact_detail_fragment.xml
> +            android:text="@string/contact_name"
для отладки есть инструмент tools. Вы можете просто использовать tools:text и lorem

2021-03-15 05:16 UTC, elestatte87 commented on app/src/main/res/layout/contact_list_fragment.xml
> +    android:layout_height="wrap_content"
match_parent

2021-03-15 05:18 UTC, elestatte87 commented on app/src/main/res/layout/contact_list_fragment.xml
> +<LinearLayout
FrameLayout нет смысла в LinearLayout
Изучите самостоятельно типы layout

2021-03-15 05:19 UTC, elestatte87 commented on app/src/main/res/layout/contact_list_fragment.xml
> +        app:layout_constraintEnd_toEndOf="parent"
Это вообще не работает так как работает с констрейнт лейаутом. Тщательно переделайте всю верстку по ПР

2021-03-15 05:25 UTC, elestatte87 commented on app/src/main/res/layout/list_contact.xml
> +<?xml version="1.0" encoding="utf-8"?>
имя лейаута лучше подправить contact_list_item.xml а то из названия не понятно что это

2021-03-17 08:27 UTC, elestatte87 commented on app/src/main/java/com/gmail/alinkahomyak/ContactDetailFragment.kt
> +    fun newInstance(id: Int) =  ContactDetailFragment().apply {
Очень странный код

2021-03-17 08:41 UTC, elestatte87 commented on app/src/main/java/com/gmail/alinkahomyak/ContactDetailFragment.kt
> +        newInstance(id)
!?

2021-03-17 08:53 UTC, elestatte87 commented on app/src/main/java/com/gmail/alinkahomyak/ContactListFragment.kt
> +                    .replace(R.id.fragmentContainer, ContactDetailFragment())
нет передачи айди

2021-03-17 09:08 UTC, elestatte87 commented on app/src/main/java/com/gmail/alinkahomyak/ContactListFragment.kt
> +    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
Перепишите полностью пожалуйста.
Здесь происходят очень странные дела.

2021-03-17 09:11 UTC, elestatte87 commented on app/src/main/java/com/gmail/alinkahomyak/ContactDetailFragment.kt
> +
?

2021-03-17 09:11 UTC, elestatte87 commented on app/src/main/java/com/gmail/alinkahomyak/ContactDetailFragment.kt
> +    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
Удалите передавайте лейаут через конструктор
    /**
     * Alternate constructor that can be used to provide a default layout
     * that will be inflated by {@link #onCreateView(LayoutInflater, ViewGroup, Bundle)}.
     *
     * @see #Fragment()
     * @see #onCreateView(LayoutInflater, ViewGroup, Bundle)
     */
    @ContentView
    public Fragment(@LayoutRes int contentLayoutId) {
        this();
        mContentLayoutId = contentLayoutId;
    }

2021-03-17 09:12 UTC, elestatte87 commented on app/src/main/java/com/gmail/alinkahomyak/ContactDetailFragment.kt
> +
а где заполнение данными ?

2021-03-21 18:19 UTC, elestatte87 commented on app/src/main/java/com/gmail/alinkahomyak/ContactDetailFragment.kt
> +        bundle?.getInt("id",id)
Я писал выше что это очень странный код (требуются правки)
я не заапрувлю этот ПР.
Вы как бы сделали все задом наперед.
Вам нужно заполнить бандл (положить айди)
и передать бандл в аргмументы фрагмента

2021-03-21 18:22 UTC, elestatte87 commented on app/src/main/java/com/gmail/alinkahomyak/ContactListFragment.kt
> +            fun newInstance (id: Int) = ContactListFragment().apply {
тут как бы уже ближе к истине. Но почитайте как работает apply
У вас тут в фигурных скобках this это уже инстанс ContactListFragment
Зачем создавать новый.

2021-03-26 10:00 UTC, thealbre requested changes

2021-03-26 10:00 UTC, thealbre commented on app/src/main/java/com/gmail/alinkahomyak/MainActivity.kt
> +        val contactListFragment = ContactListFragment()
Тут `val contactListFragment = ContactListFragment.newInstance()`

2021-03-26 10:00 UTC, thealbre commented on app/src/main/res/layout/contact_detail_fragment.xml
> +    android:id="@+id/detailFragment"
android:id должен быть не на этом месте, а выше. Попробуй сделать автоформатирование ctrl+alt+L

2021-03-26 10:00 UTC, thealbre commented on app/src/main/res/layout/contact_detail_fragment.xml
> +
от пустых строчек лучше избавиться

2021-03-26 10:00 UTC, thealbre commented on app/src/main/java/com/gmail/alinkahomyak/ContactDetailFragment.kt
> +            arguments = Bundle().apply {
замени на bundleOf{ "id" to id }. Так короче и эффективней, и не надо писать put***, оно само внутри всё подставит

2021-03-26 10:00 UTC, thealbre commented on app/src/main/java/com/gmail/alinkahomyak/ContactDetailFragment.kt
> +        newInstance(id)
это нужно убрать

2021-03-26 10:00 UTC, thealbre commented on app/src/main/java/com/gmail/alinkahomyak/ContactListFragment.kt
> +            fragmentManager!!
Выбрасывание null исключения в явном виде (`!!`) убираем. Но т.к. этот fragmentManager может быть null - то можно вместо использовать supportFragmentManager

2021-03-26 10:00 UTC, thealbre commented on app/src/main/java/com/gmail/alinkahomyak/ContactListFragment.kt
> +                .replace(R.id.fragmentContainer, ContactDetailFragment.newInstance(id))
Попробуй вынести логику навигации по экранам из самих экранов - наружу. Например для начала в MainActivity

2021-03-26 10:00 UTC, thealbre commented on app/src/main/java/com/gmail/alinkahomyak/ContactListFragment.kt
> +                .addToBackStack(null)
Если появится, например, в приложении экран с редактированием профиля - то при backStackKey == null - откроется ли экран ContactDetailFragment при нажатии на системную кнопку back?

2021-03-26 10:00 UTC, thealbre commented on app/src/main/res/layout/contact_list_fragment.xml
> +        android:id="@+id/Contact1"
Все id в xml с маленькой буквы. И лучше избегать цифр в названии, чтобы не было ситуаций, когда не знаешь чем Contact76 отличается от Contact3

2021-03-26 10:00 UTC, thealbre commented on app/src/main/res/layout/contact_detail_fragment.xml
> +
4 пустых строчек урезать до 1 или до 0

2021-03-26 10:00 UTC, thealbre commented on app/src/main/res/layout/contact_detail_fragment.xml
> +
и придерживаться этого стиля

2021-03-26 10:00 UTC, thealbre commented on app/src/main/res/layout/contact_list_fragment.xml
> +
пустая строчка и закрывающий тэг `/>` лучше держать на строчке последнего объявления параметров view/layout. Т.е. `app:layout_constraintTop_toTopOf="parent"/>`
И придерживаться этого стиля во всех xml

2021-03-29 06:52 UTC, thealbre requested changes

2021-03-29 06:52 UTC, thealbre commented on app/src/main/java/com/gmail/alinkahomyak/ContactListFragment.kt
> +            (requireActivity() as PersonClickedListener).onItemClick(1)
Хорошее правило - view не должна выбрасывать исключений, не должна ломать и крэшить всё приложение. Вся логика обработки, валидации и проверки значений\данных должна производиться в другом месте, где будет бизнес-логика приложения. Но View должна только отображать данные и больше ничего.

Отсюда нужно сделать вывод и посмотреть: если activity не будет реализовывать PersonClickedListener - то вызовется exception с невозможностью cast активити к этому интерфейсу PersonClickedListener. Получается надо сделать эту проверку nullable, и сделать `(requireActivity() as PersonClickedListener)?.onItemClick(contactId = 1)`

2021-03-29 06:52 UTC, thealbre commented on app/src/main/java/com/gmail/alinkahomyak/MainActivity.kt
> +
пустые строчки

2021-03-29 06:52 UTC, thealbre commented on app/src/main/java/com/gmail/alinkahomyak/MainActivity.kt
> +                .addToBackStack("ContactDetailFragment")
nit - это аналог "придирка", дальше буду использвоать это сокращение. Т.е. не обязательные к исправлению, но эта придирка может улучшить код

nit: Чтобы при изменении названия ContactDetailFragment.kt не искать по коду все эти места - можно написать вроде `ContactDetailFragment::class.java.simpleName`

2021-03-29 07:26 UTC, thealbre commented on app/src/main/java/com/gmail/alinkahomyak/PersonClickedListener.kt
> +    fun onItemClick(personId:Long)
Для id нет смысла использовать Long, можно использовать Int

2021-03-29 12:39 UTC, thealbre commented on app/src/main/java/com/gmail/alinkahomyak/ContactDetailFragment.kt
> +    }
Вообще, тут ещё надо добавить:
1. Вынести из `newInstance()` строчку "personId" в отдельную переменную внутри companin object `private const val PERSON_ID = "PERSON_ID"`
2. в onViewCreate получать из `requireArgument().getInt(PERSON_ID)`
3. пробрасывать значение id в слой бизнес-логики, получать оттуда данные для определённого id, и потом устанавливать данные при завершении загрузки

Но т.к. нет пока загрузки - можно сделать всё на заглушках, желательно с пробрасыванием id в какой-нибудь метод(можно прямо в ContactDetailFragment.kt), и там сетать (тестовые) данные в TextView, в ImageView. Тестовые данные можно не пихать в resources, но нужно вынести в константы\переменные этого класса, например `private const val TEST_NAME = "Maxim"` и тд.

2021-03-29 16:33 UTC, thealbre commented on app/src/main/res/layout/contact_list_fragment.xml
> +        app:layout_constraintEnd_toEndOf="parent"
тэги app:layout_constraintEnd_toEndOf, app:layout_constraintStart_toStartOf, app:layout_constraintTop_toTopOf остались ненужным грузом, после удаления ConstraintLayout. Их можно удалить)

2021-03-29 16:35 UTC, thealbre commented on app/src/main/res/layout/contact_detail_fragment.xml
> +        tools:text="@tools:sample/lorem" />
ТекстВью с точками "..." - удалить

2021-03-29 16:35 UTC, thealbre commented on app/src/main/res/layout/contact_detail_fragment.xml
> +        tools:text="@tools:sample/lorem" />
ТекстВью с точками "..." - удалить

2021-03-29 16:48 UTC, thealbre commented on app/src/main/res/values-v26/styles.xml
> +
2х пустая строчка

2021-03-29 16:48 UTC, thealbre commented on app/src/main/res/values-v26/styles.xml
> +
пустая строчка

2021-03-29 16:48 UTC, thealbre commented on app/src/main/res/values/strings.xml
> +
2х пустая строчка

2021-03-29 16:48 UTC, thealbre commented on app/src/main/res/values-v26/styles.xml
> +<resources>
Почему тут отдельный ресурс для api v26 создался? Сделай так, чтобы остался только  app/src/main/res/values/styles.xml, или какие-то тэги специфичны и требуют v26?

2021-03-29 16:48 UTC, thealbre commented on app/src/main/res/values/themes.xml
> +        <item name="colorPrimaryVariant">@color/light_orange</item>
цвета должны быть одинаковыми для colorPrimaryVariant и для colorPrimary

2021-03-29 18:07 UTC, thealbre commented on app/src/main/java/com/gmail/alinkahomyak/ContactDetailFragment.kt
> +        private const  val TEST_NAME = "Maxim"
автоформатирование класса Ctrl+Alt+L

2021-03-29 18:07 UTC, thealbre commented on app/src/main/java/com/gmail/alinkahomyak/ContactDetailFragment.kt
> +            arguments = bundleOf("PERSON_ID" to personId)
используй перменную PERSON_ID

2021-03-29 18:07 UTC, thealbre commented on app/src/main/java/com/gmail/alinkahomyak/ContactDetailFragment.kt
> +        requireArguments().getInt(PERSON_ID)
засунь результат этой строчки в перменную val personId = requireArguments().getInt(PERSON_ID)

2021-03-29 18:07 UTC, thealbre commented on app/src/main/java/com/gmail/alinkahomyak/ContactListFragment.kt
> +        private  const  val TEST_NUMBER = "79991900233"
автоформатирование класса Ctrl+Alt+L

2021-03-29 18:07 UTC, thealbre commented on app/src/main/res/layout/contact_detail_fragment.xml
> +
пустая строчка

2021-03-30 13:59 UTC, thealbre approved these changes

2021-03-30 13:59 UTC, merged